from smarthphone import Smarthphone

smarthphone = Smarthphone('Pocophone F1')
smarthphone.conectar()
smarthphone.desligar()
smarthphone.ligar()
smarthphone.conectar()
smarthphone.conectar()
smarthphone.conectar()
smarthphone.conectar()
smarthphone.desligar()
smarthphone.desconectar()
smarthphone.desligar()
smarthphone.desconectar()
smarthphone.desconectar()
smarthphone.desconectar()
smarthphone.conectar()
smarthphone.conectar()
smarthphone.conectar()
smarthphone.ligar()
smarthphone.conectar()